version: '3.4'

services:
  pheno:
    image: pheno
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090:8090
  grafana:
    image: grafana/grafana-enterprise:10.0.1
    container_name: grafana
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    ports:
      - 3000:3000
    volumes:
      - grf_data:/var/lib/grafana


volumes:
  grf_data: