version: '3.4'

services:
  pheno:
    image: pheno
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090:8090
    networks:
      - phenonet
    restart: always
  grafana:
    image: grafana/grafana-enterprise:10.0.1
    container_name: grafana
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    ports:
      - 3000:3000
    volumes:
      - grf_data:/var/lib/grafana
    networks:
      - phenonet
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest 
    container_name: prometheus 
    ports:
      - 9090:9090 
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - phenonet
    restart: unless-stopped


volumes:
  grf_data:

networks:
  phenonet: